{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# How to query for astrophysical data analysis\n",
    "\n",
    "So far I have used\n",
    "- Astropy\n",
    "- Astroquery\n",
    "- PyVO\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from astropy import table\n",
    "from astropy.coordinates import SkyCoord\n",
    "from pyvo import registry\n",
    "\n",
    "\n",
    "my_obj = SkyCoord.from_name(\"Bellatrix\")\n",
    "for res in registry.search(waveband=\"infrared\", servicetype=\"spectrum\"):\n",
    "    print(res.service.search(pos=my_obj, size=0.001))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from astroquery.ipac.nexsci.nasa_exoplanet_archive import NasaExoplanetArchive\n",
    "\n",
    "\n",
    "def query_multi_star_systems():\n",
    "    # Query the database for systems with more than one star\n",
    "    query_result = NasaExoplanetArchive.query_criteria(table=\"ps\", select=\"*\", where=\"sy_snum > 1\")\n",
    "\n",
    "    # Check if there are any results\n",
    "    if len(query_result) == 0:\n",
    "        print(\"No multi-star systems found.\")\n",
    "        return\n",
    "\n",
    "    # Get the column names and print them\n",
    "    column_names = query_result.columns\n",
    "    print(\"Column Headers:\")\n",
    "    for column_name in column_names:\n",
    "        print(column_name)\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    query_multi_star_systems()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Querying MAST STScI CAOM and ObsCore TAP service\n",
      "Querying UCL DaCHS server TAP service\n",
      "Querying The VO @ ASTRON TAP service\n",
      "Querying AIASCR VO Services TAP service\n",
      "Querying CSIRO Australia Telescope Online Archive TAP Service\n",
      "Querying CSIRO ASKAP Science Data Archive TAP Service\n",
      "  Broken: ivo://au.csiro/casda/tap (ConnectTimeout: HTTPSConnectionPool(host='casda.csiro.au', port=443): Max retries exceeded with url: /casda_vo_tools/tap/sync (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000025116306C10>, 'Connection to casda.csiro.au timed out. (connect timeout=None)'))).  Complain to James Dempsey <james.dempsey@csiro.au>.\n",
      "\n",
      "Querying VESPA PA team server TAP service\n",
      "Querying ArVO Byurakan TAP service\n",
      "Querying CADC Archive Query Service\n",
      "Querying J-PLUS DR1 Catalogue (July, 2018)\n",
      "Querying J-PLUS DR2 Catalogue (July, 2020)\n",
      "Querying J-PLUS DR3 Catalogue (July, 2022)\n",
      "Querying MINIJ-PAS PDR201912 Catalogue (December, 2019)\n",
      "Querying ChiVO TAP service\n",
      "Querying ESO TAP_OBS: a TAP service to browse and access raw and reduced data, and to query the ambient measurements, of the La Silla Paranal Observatory.\n",
      "Querying FAI archives TAP service\n",
      "Querying Planetary web services @ FUB TAP service\n",
      "Querying Laurino et al 2011 Catalog of WGE photometric redshifts for SDSS candidate qsos and galaxies\n",
      "  Broken: ivo://ia2.inaf.it/hosted/laurino2011/tap (IllegalArgumentException: Table [ ivoa.obscore ] is not found in TapSchema).  Complain to IA2 <ia2@oats.inaf.it>.\n",
      "\n",
      "Querying IAPS TAP SERVICES TAP service\n",
      "  Broken: ivo://ia2.inaf.it/tap (ConnectTimeout: HTTPConnectionPool(host='vo-node1.iaps.inaf.it', port=80): Max retries exceeded with url: /tap/sync (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000025116304050>, 'Connection to vo-node1.iaps.inaf.it timed out. (connect timeout=None)'))).  Complain to VOIAPS team (0039 06 45 48 8766) <stavro.ivanovski@iaps.inaf.it>.\n",
      "\n",
      "Querying IAP - DaCHS Services TAP service\n",
      "  Broken: ivo://iap/tap (404 Client Error: Not Found for url: http://dorotka.ufa.cas.cz//tap/sync).  Complain to David Pisa <dp@ufa.cas.cz>.\n",
      "\n",
      "Querying EVN Data Archive TAP service\n",
      "Querying JVO ALMA VO Service\n",
      "Querying AKARI Asteroid Flux Catalogue Version 1\n",
      "Querying AKARI/IRC NIR Low-resolution Spectral Catalogue of Diffuse Sky Patches\n",
      "Querying AKARI/IRC NIR Spectral Atlas of Galactic Planetary Nebulae\n",
      "Querying AKARI/IRC MIR-S slit-less spectroscopic catalogue\n",
      "Querying HALCA VSOP (the VLBI Space Observatory Programme) Correlated Data\n",
      "Querying The VSOP (the VLBI Space Observatory Programme) 5 GHz AGN (Active Galactic Nuclei) Survey Program Analysis Data\n",
      "Querying Hitomi Master Catalog\n",
      "Querying Nobeyama Radio Telescope FITS Archive\n",
      "Querying Subaru Suprime-Cam data service\n",
      "Querying KSB-ROB TAP service\n",
      "  Broken: ivo://ksb-orb.dc/tap (connection pool is closed).  Complain to Freek Verstringe <freek.verstringe@oma.be>.\n",
      "\n",
      "Querying CeSAM Virtual Observatory Server TAP service\n",
      "Querying MACHO TAP\n",
      "  Broken: ivo://nci.org.au/macho/tap (Unable to interpret query 'Unknown table \"ivoa.obscore\" ! [l.1 c.31 - l.1 c.43]\n",
      "Unknown column \"s_ra\" ! [l.1 c.14 - l.1 c.18]\n",
      "Unknown column \"s_dec\" ! [l.1 c.20 - l.1 c.25]').  Complain to NCI ASVO <asvo@nci.org.au>.\n",
      "\n",
      "Querying SkyMapper TAP\n",
      "  Broken: ivo://nci.org.au/skymapper/tap (Unable to interpret query 'Unknown table \"ivoa.obscore\" ! [l.1 c.31 - l.1 c.43]\n",
      "Unknown column \"s_ra\" ! [l.1 c.14 - l.1 c.18]\n",
      "Unknown column \"s_dec\" ! [l.1 c.20 - l.1 c.25]').  Complain to NCI ASVO <asvo@nci.org.au>.\n",
      "\n",
      "Querying WiggleZ Final Data Release TAP\n",
      "  Broken: ivo://nci.org.au/wigglez/tap (Unable to interpret query 'Unknown table \"ivoa.obscore\" ! [l.1 c.31 - l.1 c.43]\n",
      "Unknown column \"s_ra\" ! [l.1 c.14 - l.1 c.18]\n",
      "Unknown column \"s_dec\" ! [l.1 c.20 - l.1 c.25]').  Complain to NCI ASVO <asvo@nci.org.au>.\n",
      "\n",
      "Querying GAVO Data Center TAP service\n",
      "Querying PADC TAP Server on voparis-tap-astro.obspm.fr TAP service\n",
      "Querying PADC TAP Server on voparis-tap-he.obspm.fr TAP service\n",
      "Querying PADC TAP Server on voparis-rr.obspm.fr TAP service\n",
      "Querying PVOL EPN-TAP TAP service\n",
      "  Broken: ivo://pvol/tap (ConnectTimeout: HTTPConnectionPool(host='pvol2.ehu.eus', port=8083): Max retries exceeded with url: /tap/sync (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002511622C250>, 'Connection to pvol2.ehu.eus timed out. (connect timeout=None)'))).  Complain to Ricardo Hueso (Delete this line if you don't want to give it) <ricardo.hueso@ehu.eus>.\n",
      "\n",
      "Querying Cross section values TAP service\n",
      "Querying SSDC TAP Service\n",
      "  Broken: ivo://ssdc/tap (IllegalArgumentException: Table [ ivoa.obscore ] is not found in TapSchema).  Complain to SSDC Support Team <help_desk@ssdc.asi.it>.\n",
      "\n",
      "Querying ARI's Gaia TAP Service\n",
      "Querying VOXastro Data Center TAP service\n",
      "Querying TAP interface of the 3XMM-DR5 XMM-Newton Catalogue\n",
      "  Broken: ivo://xcatdb/3xmmdr5/tap (No matching interface.).  Complain to Lauretn MICHEL ((33-0) 368 852 437) <Laurent.michel@astro.unistra.fr>.\n",
      "\n",
      "Querying TAP interface of the 3XMM-dr7 XMM-Newton Catalogue\n",
      "  Broken: ivo://xcatdb/3xmmdr7/tap (TooManyRedirects: Exceeded 30 redirects.).  Complain to Laurent Michel ((33-0) 368 852 437) <Laurent.michel@astro.unistra.fr>.\n",
      "\n",
      "Querying TAP interface of the 4XMM dr13 XMM-Newton Catalogue\n",
      "  Broken: ivo://xcatdb/4xmm/tap (Incorrect ADQL query: 3 unresolved identifiers: obscore [l.1 c.31 - l.1 c.43], s_ra [l.1 c.14 - l.1 c.18], s_dec [l.1 c.20 - l.1 c.25]!\n",
      "  - Unknown table \"ivoa.obscore\" !\n",
      "  - Unknown column \"s_ra\" !\n",
      "  - Unknown column \"s_dec\" !).  Complain to Laurent Michel ((33-0) 368 852 437) <Laurent.michel@astro.unistra.fr>.\n",
      "\n"
     ]
    },
    {
     "ename": "TableMergeError",
     "evalue": "columns have different shapes",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mTableMergeError\u001b[0m                           Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[2], line 22\u001b[0m\n\u001b[0;32m     17\u001b[0m       \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m msg:\n\u001b[0;32m     18\u001b[0m           \u001b[38;5;66;03m# some service is broken; you *should* complain, but\u001b[39;00m\n\u001b[0;32m     19\u001b[0m           \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m  Broken: \u001b[39m\u001b[38;5;132;01m{}\u001b[39;00m\u001b[38;5;124m (\u001b[39m\u001b[38;5;132;01m{}\u001b[39;00m\u001b[38;5;124m).  Complain to \u001b[39m\u001b[38;5;132;01m{}\u001b[39;00m\u001b[38;5;124m.\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;241m.\u001b[39mformat(\n\u001b[0;32m     20\u001b[0m               svc_rec\u001b[38;5;241m.\u001b[39mivoid, msg, svc_rec\u001b[38;5;241m.\u001b[39mget_contact()))\n\u001b[1;32m---> 22\u001b[0m total_result \u001b[38;5;241m=\u001b[39m \u001b[43mtable\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mvstack\u001b[49m\u001b[43m(\u001b[49m\u001b[43mresults\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m     23\u001b[0m \u001b[38;5;28mprint\u001b[39m(total_result)\n",
      "File \u001b[1;32mc:\\Users\\manif\\anaconda3\\envs\\astro\\Lib\\site-packages\\astropy\\table\\operations.py:682\u001b[0m, in \u001b[0;36mvstack\u001b[1;34m(tables, join_type, metadata_conflicts)\u001b[0m\n\u001b[0;32m    679\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m tables[\u001b[38;5;241m0\u001b[39m]  \u001b[38;5;66;03m# no point in stacking a single table\u001b[39;00m\n\u001b[0;32m    680\u001b[0m col_name_map \u001b[38;5;241m=\u001b[39m OrderedDict()\n\u001b[1;32m--> 682\u001b[0m out \u001b[38;5;241m=\u001b[39m \u001b[43m_vstack\u001b[49m\u001b[43m(\u001b[49m\u001b[43mtables\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mjoin_type\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mcol_name_map\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mmetadata_conflicts\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    684\u001b[0m \u001b[38;5;66;03m# Merge table metadata\u001b[39;00m\n\u001b[0;32m    685\u001b[0m _merge_table_meta(out, tables, metadata_conflicts\u001b[38;5;241m=\u001b[39mmetadata_conflicts)\n",
      "File \u001b[1;32mc:\\Users\\manif\\anaconda3\\envs\\astro\\Lib\\site-packages\\astropy\\table\\operations.py:1481\u001b[0m, in \u001b[0;36m_vstack\u001b[1;34m(arrays, join_type, col_name_map, metadata_conflicts)\u001b[0m\n\u001b[0;32m   1477\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mNotImplementedError\u001b[39;00m(\n\u001b[0;32m   1478\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mvstack unavailable for mixin column type(s): \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mcol_cls\u001b[38;5;241m.\u001b[39m\u001b[38;5;18m__name__\u001b[39m\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m   1479\u001b[0m     )\n\u001b[0;32m   1480\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m-> 1481\u001b[0m     col \u001b[38;5;241m=\u001b[39m \u001b[43mcol_cls\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43minfo\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mnew_like\u001b[49m\u001b[43m(\u001b[49m\u001b[43mcols\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mn_rows\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mmetadata_conflicts\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mout_name\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m   1482\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m metadata\u001b[38;5;241m.\u001b[39mMergeConflictError \u001b[38;5;28;01mas\u001b[39;00m err:\n\u001b[0;32m   1483\u001b[0m     \u001b[38;5;66;03m# Beautify the error message when we are trying to merge columns with incompatible\u001b[39;00m\n\u001b[0;32m   1484\u001b[0m     \u001b[38;5;66;03m# types by including the name of the columns that originated the error.\u001b[39;00m\n\u001b[0;32m   1485\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m TableMergeError(\n\u001b[0;32m   1486\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mThe \u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;132;01m{}\u001b[39;00m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m columns have incompatible types: \u001b[39m\u001b[38;5;132;01m{}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;241m.\u001b[39mformat(\n\u001b[0;32m   1487\u001b[0m             out_name, err\u001b[38;5;241m.\u001b[39m_incompat_types\n\u001b[0;32m   1488\u001b[0m         )\n\u001b[0;32m   1489\u001b[0m     ) \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01merr\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\manif\\anaconda3\\envs\\astro\\Lib\\site-packages\\astropy\\table\\column.py:482\u001b[0m, in \u001b[0;36mColumnInfo.new_like\u001b[1;34m(self, cols, length, metadata_conflicts, name)\u001b[0m\n\u001b[0;32m    457\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mnew_like\u001b[39m(\u001b[38;5;28mself\u001b[39m, cols, length, metadata_conflicts\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mwarn\u001b[39m\u001b[38;5;124m\"\u001b[39m, name\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mNone\u001b[39;00m):\n\u001b[0;32m    458\u001b[0m \u001b[38;5;250m    \u001b[39m\u001b[38;5;124;03m\"\"\"\u001b[39;00m\n\u001b[0;32m    459\u001b[0m \u001b[38;5;124;03m    Return a new Column instance which is consistent with the\u001b[39;00m\n\u001b[0;32m    460\u001b[0m \u001b[38;5;124;03m    input ``cols`` and has ``length`` rows.\u001b[39;00m\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m    480\u001b[0m \n\u001b[0;32m    481\u001b[0m \u001b[38;5;124;03m    \"\"\"\u001b[39;00m\n\u001b[1;32m--> 482\u001b[0m     attrs \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mmerge_cols_attributes\u001b[49m\u001b[43m(\u001b[49m\n\u001b[0;32m    483\u001b[0m \u001b[43m        \u001b[49m\u001b[43mcols\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mmetadata_conflicts\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mname\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mmeta\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43munit\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mformat\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mdescription\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m)\u001b[49m\n\u001b[0;32m    484\u001b[0m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    486\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_parent_cls(length\u001b[38;5;241m=\u001b[39mlength, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mattrs)\n",
      "File \u001b[1;32mc:\\Users\\manif\\anaconda3\\envs\\astro\\Lib\\site-packages\\astropy\\utils\\data_info.py:757\u001b[0m, in \u001b[0;36mBaseColumnInfo.merge_cols_attributes\u001b[1;34m(cols, metadata_conflicts, name, attrs)\u001b[0m\n\u001b[0;32m    755\u001b[0m uniq_shapes \u001b[38;5;241m=\u001b[39m {col\u001b[38;5;241m.\u001b[39mshape[\u001b[38;5;241m1\u001b[39m:] \u001b[38;5;28;01mfor\u001b[39;00m col \u001b[38;5;129;01min\u001b[39;00m cols}\n\u001b[0;32m    756\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mlen\u001b[39m(uniq_shapes) \u001b[38;5;241m!=\u001b[39m \u001b[38;5;241m1\u001b[39m:\n\u001b[1;32m--> 757\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m TableMergeError(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mcolumns have different shapes\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[0;32m    758\u001b[0m out[\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mshape\u001b[39m\u001b[38;5;124m\"\u001b[39m] \u001b[38;5;241m=\u001b[39m uniq_shapes\u001b[38;5;241m.\u001b[39mpop()\n\u001b[0;32m    760\u001b[0m \u001b[38;5;66;03m# \"Merged\" output name is the supplied name\u001b[39;00m\n",
      "\u001b[1;31mTableMergeError\u001b[0m: columns have different shapes"
     ]
    }
   ],
   "source": [
    "from astropy import table\n",
    "from pyvo import registry\n",
    "\n",
    "QUERY = \"SELECT TOP 1 s_ra, s_dec from ivoa.obscore\"\n",
    "\n",
    "results = []\n",
    "for svc_rec in registry.search(\n",
    "          datamodel=\"obscore\", servicetype=\"tap\"):\n",
    "      print(\"Querying {}\".format(svc_rec.res_title))\n",
    "      try:\n",
    "          svc = svc_rec.get_service(\"tap\")\n",
    "          results.append(\n",
    "              svc.run_sync(QUERY).to_table())\n",
    "      except KeyboardInterrupt:\n",
    "          # someone lost their patience with a service.  Query next.\n",
    "          pass\n",
    "      except Exception as msg:\n",
    "          # some service is broken; you *should* complain, but\n",
    "          print(\"  Broken: {} ({}).  Complain to {}.\\n\".format(\n",
    "              svc_rec.ivoid, msg, svc_rec.get_contact()))\n",
    "\n",
    "total_result = table.vstack(results)\n",
    "print(total_result)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
